service: profile

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    host: http://localhost
    stages:
      - local
    edgePort: 4566
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      Lambda: http://localhost:4566
  stages:
    - local
    - prod

provider:
  name: aws
  runtime: dotnetcore3.1
  region: eu-central-1
  stage: ${opt:stage, 'local'}

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::CreateProfileAsync
    package:
      artifact: artifact/profile-lambda-csharp.zip
    environment:
      LocalStack:Config:LocalStackHost: localstack-profile # matches service name from docker-compose.yml
    events:
      - http:
          path: profile # This is the route used by the post 
          method: POST
          cors: true