service: queuereader

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    host: http://localhost
    stages:
      - local
    edgePort: 4566
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      Lambda: http://localhost:4566
  stages:
    - local
    - prod

provider:
  name: aws
  runtime: dotnetcore3.1
  region: eu-central-1
  stage: ${opt:stage, 'local'}

package:
  individually: true

functions:
  queue:
    timeout: 20
    handler: CsharpQueueHandlers::AwsDotnetCsharp.QueueHandler::ReadMessageQueueAsync
    package:
      artifact: artifact/queue-lambda-csharp.zip
    environment:
      # Config is set through appsettings.json, so the next line is not needed
      # LocalStack:Config:LocalStackHost: localstack-profile # matches service name from docker-compose.yml
    events:
      - http:
          path: receive # This is the route used by the GET 
          method: GET
          cors: true